### ISSUE TITLE
feat: Add roles compositions per number of players

### ISSUE THREAD

**Issue by akhercha** [akhercha/werewolves-of-cairo#12]
# Feature description

Depending on the number of players, we should have certain compositions possibles.
For example, for only 3 players, the composition might be: 
- 2 Townfolks,
- 1 Werewolf

It must be done for every number between 3 & 12. We can probably add multiple compositions possibles sometimes (or do it later).

# Acceptance criteria

- Compositions have been added in `src/data/compositions.cairo`

**Comment by azurwastaken** [comment]
🫡

**Comment by akhercha** [comment]
Closed by [this commit](https://github.com/akhercha/werewolves-of-cairo/commit/b84def0d874ac34e410e48e076ed29623c354f03)
